name: 'Diff poetry.lock'
description: 'Run poetry show on PRs'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
  lockfile_path:
    description: "Path to the lockfile inside the repo (defaults to 'poetry.lock')"
    default: "poetry.lock"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
